spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/map?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /page/
      suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #设置json返回日期格式
    timeZone: GMT+8   				#设置时区,否则可能前台返回时间与数据库不一致

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.kanyun.myamap.pojo
    config-locations: classpath:mybatis-conf.xml
#这个不配置也可以resource中有了logback.xml即可实现自定义日志实现
#logging:
#     config: classpath:logback-spring.xml
#     debug: true
#     level: root:DEBUG
#     path: classpath:logs
#     file: cms.log

# Server settings
server:
    port: 8080
    address: 127.0.0.1